### ISSUE TITLE
Major lag when dragging nodes with react 18 / v10.2

### ISSUE THREAD

**Issue by rayoverweij** [wbkd/react-flow#2119]
### Describe the Bug

Upgrading to React 18 and v10.2 of React Flow introduced noticeable, major lag when dragging nodes, as can be seen in the videos below.

In this example, `onNodesChange` and `onEdgesChange` are implemented as the default (calling `setNodes` and `setEdges`) and `onNodesDrag` is **not** implemented, so there shouldn't be any major logic going on on drag that could introduce this lag. I'm happy to add any code or context you might want but I'm not sure what else could be helpful here.

No other visible regressions were found when doing this update.

### Steps to Reproduce the Bug or Issue

1. Update react and react-dom to v18 and update react-flow-renderer to v10.2

### Expected behavior

I expected dragging nodes to be as fluent as when using v17/v10.1.

### Screenshots or Videos

React 17 / v10.1:

https://user-images.githubusercontent.com/24462089/166427288-07ad67ef-abd2-4973-85db-3e9c7d46456a.mp4

React 18 / v10.2:

https://user-images.githubusercontent.com/24462089/166427308-5bf9eaa2-eec5-420f-8f1f-436f5e2f4d74.mp4

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: 100.0

**Comment by stanislav-grin** [comment]
I had the same behavior when there was an additional wrapper between ReactFlowProvider and ReactFlow components, such as:
```js
<ReactFlowProvider>
  <MyOwnWrapper> // some context provider
    <ReactFlow .../>
  </MyOwnComponent>
</ReactFlowProvider>
```

When I reworked code so that become
```js
<ReactFlowProvider>
  <ReactFlow .../>
</ReactFlowProvider>
```
the issue has gone.

**Comment by moklick** [comment]
Hey @rayoverweij 

does this work for you https://codesandbox.io/s/react-flow-starter-ou8or ? Or is it also laggy?

**Comment by rayoverweij** [comment]
No, that works very well, without any lag.

**Comment by moklick** [comment]
Then a laggy codesandbox would be helpful to understand the problem better. Could you create one?

**Comment by AndrewJSchoen** [comment]
I can also chime in that I am experiencing a similar issue with lag, but in addition, it drops the position to be quite a bit further than the actual drag should cause. 

https://user-images.githubusercontent.com/5341396/166745922-3741b336-4899-42a0-a9a2-9d3677ee82c4.mov

Interestingly, though, what you see there is a package I am working on that uses RFR under the hood, and if just using the package directly in storybook, it seems to work fine ([working example](https://wisc-hci.github.io/simple-vp/?path=/story/fullscreen--fullscreen)). It is only when that component is loaded in within the larger project do you see the error in the video.

For more detail, my version of RFR is `"10.1.3-next.0"`, running on Mac/Safari/Chrome

**Comment by rayoverweij** [comment]
Okay, after a lot of testing, it seems the problem is isolated to implementing `onNodesDragStop` on `ReactFlow`. When the prop is set to _anything_, even an anonymous function `onNodesDragStop={() => {}}`, the lag occurs, and when the prop is not set, the lag does not occur. This only happens when there is a wrapper component between `<ReactFlowProvider>` and `<ReactFlow>`, and this only happens when using `createRoot()`, not with `ReactDOM.render`.

Demonstration: https://codesandbox.io/s/nostalgic-framework-6soy8u

So specific! I'm not 100% sure if there are any other props on ReactFlow that exhibit the same behaviour, but we use most of them in our implementation, and this was the only one that I found caused the lag.

**Comment by AndrewJSchoen** [comment]
I don't use `onNodeDragStop` myself, but I do use `onNodesChange`

**Comment by rayoverweij** [comment]
I wonder if we have the same issue? Looking at your video again, and given that the Storybook worked fine, it seems like the node responds to the cursor without lag but simply calculates the projected position on the flow instance wrong. At first I thought there was also lag in your video, but isn't that just `snapToGrid` set to true (which is false in my case)?

(I might be completely off there, but the fact remains that there's something off about `onNodeDragStop`.)

**Comment by AndrewJSchoen** [comment]
That is an interesting observation. I can test in a bit with my setup to see if turning snapping off fixes the issue.

**Comment by samanrnr** [comment]
I have exactly the same problem. I mentioned that in #2081

**Comment by rayoverweij** [comment]
Yep, your issue (though not the OP issue in 2081) seems to give the exact same behaviour. @samanrnr what does your code look like? Do you also have `onNodeDragStop` implemented and/or a wrapper div between `ReactFlowProvider` and `ReactFlow`?

**Comment by AndrewJSchoen** [comment]
A bit of an update on my end. Removing `snapToGrid` does not seem to resolve the larger-than-expected offset value issue I was seeing when using react-18 and react-18-style rendering. However, even when just using 18 with 17-style rendering, I now do see a non-trivial amount of lag. Also, if it isn't clear, I also have a wrapper div between ReactFlowProvider and ReactFlow.

**Comment by samanrnr** [comment]
It's my code: 
`<ReactFlowProvider>
      <div className="reactflow-wrapper" ref={reactFlowWrapper}>
        <ReactFlow
          fitView
          fitViewOptions={{includeHiddenNodes: false, maxZoom: 0.5}}
          snapToGrid
          snapGrid={[15, 15]}
          nodes={nodes} 
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onDrop={onDrop}
          onConnect={onConnect}
          onInit={onInit}
          onDragOver={onDragOver}
          onNodeDragStart={clearSelection}
          minZoom={0.2}
        >
             <Controls />
            <Background color='#6C757D' />
        </ReactFlow>
      </div>
</ReactFlowProvider>`

**Comment by samanrnr** [comment]
I also tried the 'stress' example of official documentation. The lag occurs there too.

**Comment by dineshsalunke** [comment]
I am also facing similar issues mentioned above, lag and exponential position changes.
I am also using React 18 and RFR v10.2.1.

I noticed the position change issue happens if we have createRoot api from react 18, If I shift back to ReactDOM.render api then the issue is fixed.

I still haven't got time to investigate completely into this yet, but for now based on the react blog for v18 seems the issue might be related to the new concurrent mode

**Comment by rayoverweij** [comment]
Fwiw, can confirm the issue remains on 10.2.2.

@moklick just icymi, I narrowed it down and have a codesandbox here: https://codesandbox.io/s/nostalgic-framework-6soy8u

**Comment by moklick** [comment]
@rayoverweij We are working on an update that replaces react-draggable with d3-drag (which is already a dependency, because we are using d3-zoom). In that version we are no longer work with deltas for the drag events but the absolute mouse position. You can check out the branch `refactor/d3-drag`. Is that one still laggy for you?

**Comment by rayoverweij** [comment]
@moklick I tried to use it but it crashed on render:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/24462089/167614067-3957d1fe-bcea-4dbb-a9e2-668643470112.png">

**Comment by dineshsalunke** [comment]
@moklick checked the branch and everything seems to be working fine

**Comment by moklick** [comment]
@rayoverweij you can try the new version by installing `react-flow-renderer@next`

**Comment by rayoverweij** [comment]
@moklick Thanks! The above error didn't occur now and the lag is gone, yay 😊

In my quick testing, I did run into three other issues:

1. On every other drag, when releasing a node, it would snap back to its original position. So if I drag a node, it'll snap back; if I drag it again, it'll stay put; if I drag it a third time, it'll snap back (to it's "secondary" position, not its initial one), and so forth.
2. I get an error that `store.selectedNodesBbox` doesn't exist anymore - has this been replaced?
3. On my custom edge, I had been passing down a `style` prop of (TypeScript) type `React.CSSProperties?` which now throws an error, and (without investigating much) I had to change it to `any` to work.

These are unrelated to the lagging issue, and I'm not sure to what extent you're already aware of (some of) them, but I did want to report them real quick. I'd share more details but I couldn't select v10.2.3-next.1 yet in codesandbox.

As far as I'm concerned, this issue is resolved, though!

**Comment by moklick** [comment]
Hey @rayoverweij , unfortunately I can't reproduce any of the bugs you mentioned.  

1. Did you tested this with a controlled or uncontrolled flow?
2. I removed `selectedNodesBbox` because [it wasn't used anywhere in the current version](https://github.com/wbkd/react-flow/search?q=selectedNodesBbox). How did you get this error? 
3. There are no changes for the edge types `style` is still `React.CSSProperties` https://github.com/wbkd/react-flow/blob/refactor/d3-drag/src/types/edges.ts#L21

**Comment by rayoverweij** [comment]
@moklick 

1. Controlled. `onNodeDragStop` is implemented and syncs the new position of the node with Firebase;  `onNodeDrag` is not implemented
2. Through `useStore(store => store.selectedNodesBbox)`; it's used in a custom copy/paste implementation that saves the Rect with the copied nodes and uses it to calculate the correct position offset when pasting. It's been a while since I added this so I'd have to look how easy it is to rewrite the methods without it
3. This one seems to have mysteriously vanished after restarting my editor - probably a TypeScript or VSCode quirk

**Comment by samanrnr** [comment]
Thanks. it solved the issue!

**Comment by AndrewJSchoen** [comment]
@moklick I am getting an error with the `next` version such that when I click on a node in certain circumstances, but I am not quite sure what is causing it. Here is the error I am getting:

```
[Error] TypeError: event.target.className.includes is not a function. (In 'event.target.className.includes(noDragClassName)', 'event.target.className.includes' is undefined)
	(anonymous function) (vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_lib_runtime_RefreshUtils_js-node_mod-fbcf8b.iframe.bundle.js:135885:92)
	mousedowned (vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_lib_runtime_RefreshUtils_js-node_mod-fbcf8b.iframe.bundle.js:168211)
	(anonymous function) (vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_lib_runtime_RefreshUtils_js-node_mod-fbcf8b.iframe.bundle.js:170244)
```

It also seems to have broken my dragging capability completely (controlled), but I am working on figuring out if that is on me or the library.

**Comment by moklick** [comment]
Can you create a codesandbox for these issues? I am testing the next version with chrome, ff and safari and can't repro any of these issues.

**Comment by AndrewJSchoen** [comment]
> Can you create a codesandbox for these issues? I am testing the next version with chrome, ff and safari and can't repro any of these issues.

Sure. I will probably spin that off in a separate issue or comment on the pull request (your preference).

**Comment by moklick** [comment]
A separate issue is fine! Thanks!

**Comment by rayoverweij** [comment]
Hi @moklick - is there a way to access the preview release in codesandbox? I can see `@next` versions for 10.0 and 10.1 but not 10.3, and I'd like to try and make a repro'able environment for a new issue.

In short, though, in my code I implement a few handlers (`onNodeDragEnd`, `onSelectionDragEnd`, and `onNodesDelete`) that will push `nodes` and `edges` to Firebase. It seems that as of 10.2.3, the most recent changes from `onNodesChange` don't happen before these handlers are called anymore, so the changes are only processed when the handler is called again. This sounds very similar to or at least related to what @AndrewJSchoen was describing.

Anyway, happy to try and find out more (and open a separate issue) but it seems that I can't use this version yet in codesandbox.

**Comment by AndrewJSchoen** [comment]
@moklick I had also been noticing that in addition to the `onNodeChange` api change mentioned above, my nodes still weren't dragging correctly, even when they should have been (based on what worked in the previous version). It seems this is related to having the `elementsSelectable` prop set to false. Is this intended?

**Comment by moklick** [comment]
That change was not intended @AndrewJSchoen ;) Could you check `10.2.4-next.1`?

**Comment by AndrewJSchoen** [comment]
@moklick Yes, this is now working in that release.

**Comment by rayoverweij** [comment]
Hi @moklick - the "nodes snapping back" issue was fixable with some refactoring on my end, and I could easily replace `selectedNodesBBox` with `getRectOfNodes` on the selected elements, so that's all my issues here fixed :) 10.2.4-next.1 is working perfectly for me.

Thanks for all your help throughout this thread!

**Comment by moklick** [comment]
released in v10.3.0
