### ISSUE TITLE
the browser's Console has warnings:Default export is deprecated,Instead use import {shallow} from 'zustand/shallow

### ISSUE THREAD

**Issue by codingCenterFar** [wbkd/react-flow#3494]
### Describe the Bug

the browser's Console has warnings:Default export is deprecated,Instead use import {shallow} from 'zustand/shallow,that cause a program to stall

### Steps to Reproduce the Bug or Issue

1、yarn install the latest version of the reactflow;
2、yarn start any example and  we will see the warning on the browser console

### Expected behavior

can't see the warning:Default export is deprecated,Instead use import {shallow} from 'zustand/shallow

### Platform

zustand:4.4.3
reactflow:11.9.3

**Comment by codingCenterFar** [comment]
i think it was caused by the zustand version,because i have used the reactflow:11.8.3 and zustand:4.4.1,the result is right

**Comment by moklick** [comment]
this issue is fixed in the latest version

**Comment by codingCenterFar** [comment]
> this issue is fixed in the latest version

OK,Thank you!

**Comment by codingCenterFar** [comment]
> this issue is fixed in the latest version

i have tried to reinstall the latest version:11.9.3,but I still can see the same warning

**Comment by elmanAliev** [comment]
I have the same problem. the browser's Console has warnings:Default export is deprecated,Instead use import {shallow} from 'zustand/shallow
reactflow:11.9.3

**Comment by moklick** [comment]
Did you remove node modules and package lock and installed again?

**Comment by codingCenterFar** [comment]
> Did you remove node modules and package lock and installed again?

Yes,I did as above,but can't solve the problem

**Comment by bgramaje** [comment]
I am having the same issue as above

**Comment by bgramaje** [comment]
Hey, thanks for the answer. I cannot reproduce it since it is confidencial code.

This is the error I am having: shallow.js:86  [DEPRECATED] Default export is deprecated. Instead use `import { shallow } from 'zustand/shallow'`. 
    at UserSelection (/node_modules/@reactflow/core/dist/esm/index.js:2152:56)
    at div
    at eval (/node_modules/@reactflow/core/dist/esm/index.js:2299:22)
    at div
    at ZoomPane (/node_modules/@reactflow/core/dist/esm/index.js:1894:21)
    at FlowRenderer (/node_modules/@reactflow/core/dist/esm/index.js:3026:25)
    at GraphView (/node_modules/@reactflow/core/dist/esm/index.js:3677:22)
    at Wrapper (/node_modules/@reactflow/core/dist/esm/index.js:3976:20),

Updated to latest version of react-flow and also zustand is fixed to 4.3.9, which you answered in other issue.

Thanks

**Comment by bgramaje** [comment]
This is causing my console to be floaded and affecting to the reactflow diagram performance

**Comment by bgramaje** [comment]
> Hey, thanks for the answer. I cannot reproduce it since it is confidencial code.
> 
> This is the error I am having: shallow.js:86 [DEPRECATED] Default export is deprecated. Instead use `import { shallow } from 'zustand/shallow'`. at UserSelection (/node_modules/@reactflow/core/dist/esm/index.js:2152:56) at div at eval (/node_modules/@reactflow/core/dist/esm/index.js:2299:22) at div at ZoomPane (/node_modules/@reactflow/core/dist/esm/index.js:1894:21) at FlowRenderer (/node_modules/@reactflow/core/dist/esm/index.js:3026:25) at GraphView (/node_modules/@reactflow/core/dist/esm/index.js:3677:22) at Wrapper (/node_modules/@reactflow/core/dist/esm/index.js:3976:20),
> 
> Updated to latest version of react-flow and also zustand is fixed to 4.3.9, which you answered in other issue.
> 
> Thanks


This is causing my console to be floaded and affecting to the reactflow diagram performance

**Comment by tmarnet** [comment]
I'm having the same issue after installing the latest version of `reactflow` in a project:

| Screenshot 1 | Screenshot 2 |
|--------|--------|
| <img width="537" alt="Screenshot 2023-10-16 at 9 21 03 AM" src="https://github.com/wbkd/react-flow/assets/10536410/d0efe28f-3a57-4b79-9f26-473b3ccd814f"> | <img width="535" alt="Screenshot 2023-10-16 at 9 21 23 AM" src="https://github.com/wbkd/react-flow/assets/10536410/54f6b320-9194-4bcc-a608-26ba10c51b44"> | 

I don't really care about the console bloating, but it definitely introduces performance issues, as mentioned in the previous comment.

I was unable to reproduce on Codesandbox using the link in the issue template. My project is quite old and is running on Webpack 4, maybe there's something on that side ?

**Comment by AdamHG2411** [comment]
I'm also still seeing this after updating to the latest version (deleted node_modules and package-lock, then reinstalled and confirmed I'm using `11.9.4` of reactflow). My project is bundling with Parcel, so I don't think this is related to Webpack 4 as the previous person mentioned.

For a sense of scale, I get 516 of those warnings when the page initially loads, and thousands more as I drag nodes around. This is for a simple diagram with 2 nodes. I didn't have this issue Friday. Noticed it first thing this morning and then updated.

**Comment by codingCenterFar** [comment]
> We are not using the default export anywhere in the library. Could you create a codesandbox or send me a repo link?
Can you reproduce the problem?Based on the comments above, there are a lot of people with the same problem.Will it be addressed in the next release?

**Comment by moklick** [comment]
This is really weird. We are not using the deprecated default export anymore. Can you reproduce this with a codesandbox or send a repo?

**Comment by codingCenterFar** [comment]
> This is really weird. We are not using the deprecated default export anymore. Can you reproduce this with a codesandbox or send a repo?
I apologize for not being able to reproduce it through  codesandbox.But i have saw the same description in the sourcecode:https://github.com/pmndrs/zustand/blob/v4.4.3/src/shallow.ts,you can see this in line8

**Comment by moklick** [comment]
Sure. I know about that deprecation warning. After they introduced it, we changed our imports to named ones. Are you sure, that you are using the latest reactflow version?

**Comment by codingCenterFar** [comment]
> Sure. I know about that deprecation warning. After they introduced it, we changed our imports to named ones. Are you sure, that you are using the latest reactflow version?

Yes,I am sure.I use the version is 11.9.4

**Comment by gcouch-interlinx** [comment]
I am having the same issue with version 11.9.4

**Comment by moklick** [comment]
Can anyone here create an example for this issue. I can't reproduce it. As you can see here, we are not using the shallow default export anywhere https://github.com/search?q=repo%3Awbkd%2Freact-flow+shallow&type=code&p=1

**Comment by AdamHG2411** [comment]
Sorry for the delay. Had to focus on other tasks yesterday. Here's a demo repo where I've recreated the bug. I see the warnings in both Chrome and Firefox.

https://github.com/griderweb/reactflow-warning-demo

**Comment by moklick** [comment]
Thanks @AdamHG2411! It seems to be an issue with [Parcel and Zustand](https://codesandbox.io/s/parcel-forked-496h8z?file=/src/index.js). As you can see, the warning gets printed event if the import is correct. I opened a bug report: https://github.com/pmndrs/zustand/discussions/2133

**Comment by AdamHG2411** [comment]
Thanks! It looks like that PR has been merged. I think now you probably just need to update to v4.4.4 of zustand?

**Comment by moklick** [comment]
@AdamHG2411 if you remove node_modules and package-lock.json and run npm install again it, it should work. We are not pinning the zustand version in our package.json.

**Comment by moklick** [comment]
This is fixed by Zustand 4.4.4 - you might need to remove node_modules and package-lock.json, before you `npm install` again.

**Comment by codingCenterFar** [comment]
> This is fixed by Zustand 4.4.4 - you might need to remove node_modules and package-lock.json, before you `npm install` again.

OK,Thank you very much!
